"""
Even Fibonacci numbers
========================================================================================================================
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
========================================================================================================================
"""

from ..helper_functions import HelperFunctions as Hf

sum_fib = 0
x = 0
fib = Hf.fibonacci(x)
while fib < 4000000:
    x += 1
    fib = Hf.fibonacci(x)
    if fib % 2 == 0:
        sum_fib += fib

print sum_fib